# Generated by Django 4.0 on 2022-05-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='desc',
            new_name='Desc',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='Name',
        ),
    ]
